const ActionType = {
  DEFAULT: 0,
  ADD_PROFILE: 1,
  REMOVE_PROFILE: 2,
  ADD_PALETTE: 3,
  REMOVE_PALETTE: 4,
  ADD_PARTICIPANT: 5,
  REMOVE_PARTICIPANT: 6,
  UPDATE_DISH_PRICE: 7,
  UPDATE_PARTICIPANT_PRICE: 8,
  UPDATE_TAX_DISCOUNT: 9,
  UPDATE_PALETTE_FOODNAME:10
};

module.exports = ActionType;
